// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ItemTable, ItemTableData, ItemTableTableId } from "./tables/ItemTable.sol";
import { InventoryTable, InventoryTableData, InventoryTableTableId } from "./tables/InventoryTable.sol";
import { UserTable, UserTableData, UserTableTableId } from "./tables/UserTable.sol";
