// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

enum TenderType {
  CASH,
  DEBIT,
  CREDIT,
  CRYPTO
}

enum TransactionType {
  BUY,
  REFUND,
  VOID,
  SUSPEND
}

enum PaymentStatus {
  PAID,
  PENDING,
  PARTIAL
}

enum DiscountType {
  PERCENTAGE,
  AMOUNT
}

enum CustomerType {
  NONE,
  MEMBER
}
