// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IInventorySystem {
  function addItem(
    uint256 itemId,
    string memory name,
    uint256 price,
    uint256 salePrice,
    uint256 quantity,
    string memory location
  ) external;

  function updateItemName(uint256 itemId, string memory name, string memory location) external;

  function updateItemPrice(uint256 itemId, uint256 price, string memory location) external;

  function updateItemSalePrice(uint256 itemId, uint256 salePrice, string memory location) external;

  function updateItemQuantity(uint256 itemId, uint256 quantity, string memory location) external;

  function removeItem(uint256 itemId, string memory location) external;
}
